# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blo',
        ),
    ]
